export type FontWeight = '100' | '400' | '500' | '700'
export type FontSize =
  | '3xs'
  | '2xs'
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
export type TextAlign = 'left' | 'center' | 'right' | 'justify'
